### ISSUE TITLE
Error from 2D Case When Running from Scratch

### ISSUE THREAD

**Issue by tab881** [cics-nd/ar-pde-cnn#4]
Hello,

I'm really interesting in your work, so I tried to run it. However, when I test the code for the 2D Burgers case, I got following errors. I guess there should be some errors for the DenseNet, particularly the size for kernel, stride and padding (especially the 'circular padding' you used). By the way, I used the dataset you provided to train it from scratch.

Thanks,

>>> Training network, lets rock
Traceback (most recent call last):
  File "main.py", line 267, in <module>
    tsteps, tback, tstart, dt)
  File "main.py", line 61, in train
    uPred = model(input[:,-2*args.nic:,:])
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "=/Desktop/ar-pde-cnn-master/2D-Burgers-SWAG/nn/swag.py", line 67, in forward
    return self.base(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Desktop/ar-pde-cnn-master/2D-Burgers-SWAG/nn/bayesNN.py", line 75, in forward
    output = self.model(input)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Desktop/ar-pde-cnn-master/2D-Burgers-SWAG/nn/denseEDcirc2d.py", line 314, in forward
    return self.features(x)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Desktop/ar-pde-cnn-master/2D-Burgers-SWAG/nn/denseEDcirc2d.py", line 68, in forward
    return torch.cat([x, y], 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 35 and 37 in dimension 2 (The offending index is 1)

**Comment by NickGeneva** [comment]
Verify your PyTorch version matches the one specified in the main readme. As noted, there was a change in the convolutional padding in newer PyTorch versions that requires edits to the model (minor but required). Problems like this tend to stem from using a wrong version of PyTorch.

**Comment by tab881** [comment]
> Verify your PyTorch version matches the one specified in the main readme. As noted, there was a change in the convolutional padding in newer PyTorch versions that requires edits to the model (minor but required). Problems like this tend to stem from using a wrong version of PyTorch.

OK, I installed a different version of torchvision. I guess if I still use the newest pytorch but change the network structure (i.e., kernel, stride, padding) accordingly to make it work, the result still will be good since the autoregressive strategy and Sobel filter should be working as expected.

Thanks,

**Comment by NickGeneva** [comment]
Glad you got it working!
